// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAey6nvnvQc0hQvw-W9ZWrcuHCfPPU17cI',
    appId: '1:60681693325:web:500d8f908cd753c0da9ac4',
    messagingSenderId: '60681693325',
    projectId: 'ipl2026-dafa1',
    authDomain: 'ipl2026-dafa1.firebaseapp.com',
    storageBucket: 'ipl2026-dafa1.firebasestorage.app',
    measurementId: 'G-6XJZ79QZ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUwgWOC_hGuNxQ9nXqZcWPC5RFQaN2zc',
    appId: '1:60681693325:android:a06104488d9af3ebda9ac4',
    messagingSenderId: '60681693325',
    projectId: 'ipl2026-dafa1',
    storageBucket: 'ipl2026-dafa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcszh4wqizZHfikr2Ylb591HEjklo2D-A',
    appId: '1:60681693325:ios:21c28f4cc7585f0fda9ac4',
    messagingSenderId: '60681693325',
    projectId: 'ipl2026-dafa1',
    storageBucket: 'ipl2026-dafa1.firebasestorage.app',
    iosBundleId: 'com.example.ipl2026',
  );
}
